version: '3'
services:
  web:
    stdin_open: true
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./volumen:/opt/minecraft
    networks:
      - mine_network

networks:
  mine_network:
    external: true
  
