version: '3'
services:
  servidor:
    stdin_open: true
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./volumen:/opt/server
    networks:
      - server_network

networks:
  server_network:
    external: true
  
